


booklist=[[3205,'The City','aa'],
            [3209,'The Trip','aa'],
            [3241,'Some Plants','aa'],
            [3211,'My Sweets','aa'],
            [3219,'The Beach','aa'],
            [3200,'The Zoo','aa'],
            [3201,'Big Things','aa'],
            [3203,'I Love Cats','aa'],
            [3204,'Little Things','aa'],
            [3210,'Colorful Balls','aa'],
            [3216,'Animals Nap','aa'],
            [3237,'We Are Workers','aa'],
            [3228,'We Can Touch','aa'],
            [3451,'Baking Soda Experiment','B'],
            [3427,'Night Sky Wonders','B'],
            [3439,'We Eat Cookies','B'],
            [3419,'Butterfly Dance','B'],
            [3488,'Cactus in the Desert','B'],
            [3493,'Transportation','B'],
            [3442,'Go After a Dog','B'],
            [3449,'Ice-cream Delight','B'],
            [3444,'Learning to Share','B'],
            [3418,'Emmas Playful Cat','B'],
            [3440,'Sheep Facts','B'],
            [3484,'The Busy Farmer','B'],
            [3430,'The Mexican Festival','B'],
            [3447,'The Shopping Trip','B'],
            [3496,'The Solar System','B'],
            [3495,'The Wonderful World of Drinks','B'],
            [3467,'Butterfly','B'],
            [3457,'Earths Oceans','B'],
            [3481,'Lions','B'],
            [3465,'Unicorn Magic','B'],
            [3490,'Apple','B'],
            [3492,'Fruit around the World','B'],
            [3483,'Fruits and Vegetables','B'],
            [3498,'Happy Feelings','B'],
            [3417,'Maxs Dinosaur Discoveries','B'],
            [3432,'The Lost Panda','B'],
            [3421,'A Fairy in the Forest','B'],
            [3433,'A Trip','B'],
            [3471,'Adventures in Travel','B'],
            [3416,'Around the World','B'],
            [3414,'Best Friends Forever','B'],
            [3475,'Oceans','B'],
            [3479,'Reptiles and Amphibians','B'],
            [3422,'The Rainbow Surprise','B'],
            [3412,'Lilys Dream Land','B'],
            [3459,'Staying Safe','B'],
            [3415,'The Bunny','B'],
            [3406,'Brave Little Boy','B'],
            [3487,'Canned Food','B'],
            [3458,'Cars','B'],
            [3485,'Growing Up','B'],
            [3477,'Plants Grow','B'],
            [3443,'Sunflower Magic','B'],
            [3404,'The Busy Bee','B'],
            [3461,'The Spider','B'],
            [3474,'Abraham Lincoln','B'],
            [3453,'Martin Luther King Jr.','B'],
            [3401,'Mermaid Friends','B'],
            [3413,'My Dream Job','B'],
            [3407,'The Little Acorns Journey','B'],
            [3489,'All about Bananas','B'],
            [3469,'Jobs around Us','B'],
            [3472,'Lets Go Fishing','B'],
            [3482,'Monkeys','B'],
            [3436,'The Rose','B'],
            [3428,'Timmys Jungle Adventure','B'],
            [3409,'An Unforgotten Day','B'],
            [3480,'Birds in the Sky','B'],
            [3468,'Doctor','B'],
            [3429,'My Artistic Family','B'],
            [3424,'Springtimes Awakening','B'],
            [3456,'The Earth','B'],
            [3497,'Animal Sounds','B'],
            [3437,'Be a Change Maker','B'],
            [3410,'Dreamland Adventure','B'],
            [3454,'Learning to Read','B'],
            [3431,'Little Learners','B'],
            [3426,'The Lost Toys','B'],
            [3411,'Be Kind','B'],
            [3445,'Be Thankful All Year Round','B'],
            [3420,'Beautiful Forest','B'],
            [3470,'Building Materials','B'],
            [3448,'Little Gratitude','B'],
            [3446,'The Brave Bunny','B'],
            [3425,'The Little Singer','B'],
            [3408,'The Wandering Seed','B'],
            [3491,'Famous Landmarks','B'],
            [3423,'The Picnic','B'],
            [3460,'Mooncake','B'],
            [3405,'The Brave Squirrel','B'],
            [3435,'The New Girl','B'],
            [3403,'The Space Robot','B'],
            [3400,'The Girls Quest','B'],
            [3438,'The Tree and the Magpie','B'],
            [3441,'My Birthday','B'],
            [3466,'My Friends','B'],
            [3462,'Colors of the World','B'],
            [3508,'Sports','C'],
            [3571,'Cleopatra','C'],
            [3575,'Food Groups','C'],
            [3581,'Blindness','C'],
            [3578,'Elephants','C'],
            [3589,'Imagination','C'],
            [3576,'Insects','C'],
            [3582,'Cultures','C'],
            [3591,'Trash','C'],
            [3569,'Dragons','C'],
            [3550,'Ocean','C'],
            [3559,'Money','C'],
            [3566,'Tools','C'],
            [3568,'The Human Body','C'],
            [3590,'Clean Up','C'],
            [3558,'Safety at Home','C'],
            [3563,'Feelings','C'],
            [3573,'Weather','C'],
            [3557,'Cars','C'],
            [3561,'Jogging','C'],
            [3562,'Cinderalla','C'],
            [3523,'The Zoo','C'],
            [3588,'Time Management','C'],
            [3509,'Magic Forest','C'],
            [3548,'Grow up','C'],
            [3553,'Dinosaurs','C'],
            [3574,'Mountains','C'],
            [3525,'Art Show','C'],
            [3526,'The Firefighter','C'],
            [3577,'Birds','C'],
            [3519,'Sushi Time','C'],
            [3545,'Art Class Fun','C'],
            [3564,'Doctors','C'],
            [3565,'Computers','C'],
            [3527,'The Apple Tree','C'],
            [3530,'Beach Day','C'],
            [3579,'Colors','C'],
            [3516,'My Dream','C'],
            [3586,'Communication','C'],
            [3592,'Snakes','C'],
            [3596,'Electric Vehicle','C'],
            [3546,'Ocean Exploration','C'],
            [3585,'Learning Styles','C'],
            [3580,'Shy Sherman','C'],
            [3518,'First Day of School','C'],
            [3531,'Little Butterfly','C'],
            [3541,'Night Sky','C'],
            [3552,'Frozen Water','C'],
            [3587,'Morning Meal','C'],
            [3512,'Climbing to the Top','C'],
            [3514,'Forgiveness Is Magic','C'],
            [3524,'I Am Unique','C'],
            [3599,'Vaccine','C'],
            [3507,'The Rainbow Bridge','C'],
            [3515,'Helping Hand','C'],
            [3547,'The Big Race','C'],
            [3502,'Arctic Birds','C'],
            [3520,'The Magic of Books','C'],
            [3556,'Everyday Home Appliances','C'],
            [3597,'Aging','C'],
            [3598,'Eating Diets','C'],
            [3503,'Time Travel Adventure','C'],
            [3540,'Thankful Day','C'],
            [3551,'Pairs','C'],
            [3506,'The Lost Kite','C'],
            [3521,'Colorful Friends','C'],
            [3522,'Earth Day Cleanup','C'],
            [3567,'Time','C'],
            [3593,'The Big Ben','C'],
            [3529,'Lost in the Woods','C'],
            [3501,'Summer Plans','C'],
            [3505,'The Brave Little Bunny','C'],
            [3533,'The Ugly Duckling','C'],
            [3595,'Virtual Reality','C'],
            [3500,'The Unusual Guests','C'],
            [3539,'Cooking','C'],
            [3504,'The Mysterious Saboteur','C'],
            [3534,'Nature Walk','C'],
            [3517,'The Big Climb','C'],
            [3542,'My Own Way','C'],
            [3510,'Lost Toy','C'],
            [3549,'Sundown','C'],
            [3535,'The Unyielding Steed','C'],
            [3538,'The New Song','C'],
            [3544,'Fall Colors','C'],
            [3537,'Transportation','C'],
            [3528,'Cities','C'],
            [3532,'Amusement Parks','C'],
            [3511,'A Happy Day','C'],
            [3570,'Egg Hunting Fun','C'],
            [3536,'I Love Dance','C'],
            [3643,'The Art Show','D'],
            [3640,'Space Adventure','D'],
            [3647,'Around the World','D'],
            [3679,'My Pet Bunny','D'],
            [3649,'Reading Time','D'],
            [3662,'I Like China','D'],
            [3624,'The Lost Kite','D'],
            [3665,'The Lost Wallet','D'],
            [3667,'The Rabbit','D'],
            [3670,'Find the Kite','D'],
            [3608,'The Magical Castle','D'],
            [3620,'The Magic Hat','D'],
            [3634,'Mermaid','D'],
            [3653,'Making Friends','D'],
            [3673,'Amelia Earhart','D'],
            [3683,'Plants','D'],
            [3638,'Time-Travel','D'],
            [3656,'Happy Tears','D'],
            [3660,'Cars','D'],
            [3629,'The Pumpkin','D'],
            [3641,'The Great Wall','D'],
            [3642,'Be a Rainbow','D'],
            [3655,'Rainy Day','D'],
            [3607,'The Magic Shoes','D'],
            [3619,'The Big Ben','D'],
            [3626,'The Frog and the Lily Pad','D'],
            [3689,'Drinks','D'],
            [3644,'Try Something New','D'],
            [3666,'Lost in the Jungle','D'],
            [3696,'Flowers','D'],
            [3617,'Musicians','D'],
            [3645,'The Growth of Seeds','D'],
            [3646,'Beijing','D'],
            [3658,'Trees','D'],
            [3635,'The Enchanted Castle','D'],
            [3699,'The Fox','D'],
            [3605,'The Adventure of the Lost Kitten','D'],
            [3612,'The Magic Seed','D'],
            [3651,'The Singing Bird','D'],
            [3610,'The Magic Key','D'],
            [3637,'The Robot Planet','D'],
            [3627,'Lilys Shopping Adventures','D'],
            [3613,'Basketball Dream','D'],
            [3615,'Farmers','D'],
            [3623,'The Lost Hat','D'],
            [3632,'Playtime at the Park','D'],
            [3677,'Mammals','D'],
            [3676,'Bird Types','D'],
            [3650,'The Magic Box','D'],
            [3628,'The Butterfly Garden','D'],
            [3604,'The Four Seasons','D'],
            [3621,'The Garden Party','D'],
            [3664,'Exercise','D'],
            [3609,'Astronauts','D'],
            [3611,'Life Cycle of a Butterfly','D'],
            [3633,'Various Hobbies','D'],
            [3663,'Kindness','D'],
            [3672,'Where Animals Live','D'],
            [3614,'Body Parts','D'],
            [3659,'Earths Treasures','D'],
            [3675,'Reptiles','D'],
            [3654,'A Visit to the Museum','D'],
            [3636,'An Unusual Gift','D'],
            [3652,'Where Plants Grow','D'],
            [3678,'Animal Homes','D'],
            [3690,'Foxes','D'],
            [3600,'Veterinarians','D'],
            [3618,'Bens Ball','D'],
            [3631,'The Sock','D'],
            [3693,'How Do They Swim','D'],
            [3695,'Fishes','D'],
            [3692,'Senses','D'],
            [3648,'A Day at the Park','D'],
            [3682,'The History of Red Cross','D'],
            [3602,'Healthy Food','D'],
            [3657,'Forest Animals','D'],
            [3671,'Doctors','D'],
            [3694,'The Importance of Breakfast','D'],
            [3606,'Dinosaurs','D'],
            [3686,'Bill Gates','D'],
            [3661,'Colors','D'],
            [3685,'Firefighter','D'],
            [3691,'Country Places','D'],
            [3630,'The Little Girl Picking Flowers','D'],
            [3697,'Cranberries','D'],
            [3684,'Penguin','D'],
            [3698,'Bubbles','D'],
            [3668,'The Lost Umbrella','D'],
            [3601,'The Solar System','D'],
            [3680,'The Different Types of Clouds','D'],
            [3681,'The Parts of a Flower','D'],
            [3639,'The Joy of Travel','D'],
            [3687,'How to Avoid Earthquake','D'],
            [3688,'Famous Scenic Spots','D'],
            [3731,'Anna and Her Dog','E'],
            [3732,'Amazing Trees','E'],
            [3734,'Mermaids Treasure Hunt','E'],
            [3815,'Lets Go Pick a Lotus','F'],
            [3880,'What is Weather','F'],
            [3864,'Who are the Dinosaurs','F'],
            [3857,'How many eggs can a person eat in a day','F'],
            [3991,'Carbonated Beverages','G'],
            [3978,'Computers','G'],
            [3982,'Washing Hands','G'],
            [4080,'Learning about Money','H'],
            [4071,'A Peek inside Where Creatures Live','H'],
            [4062,'Why Do Elephants Have Trunks','H'],
            [4084,'All about Volcanoes','H'],
            [4087,'Essential Household Appliances','H'],
            [4089,'Discovering India','H'],
            [4103,'The Dimension under the School','I'],
            [4105,'Nina and the Lost City of Atlantis','I'],
            [4113,'Archaeologist Dr. Smith and an Egyptian Tomb','I'],
            [4169,'All about Jellyfish','I'],
            [4167,'Secrets of Soil','I'],
            [4131,'Welcome to Ancient Egypt','I'],
            [4220,'Dazzling Dinosaurs Giants of the Prehistoric World','J'],
            [4254,'Hugs for Mommy','J']]


bookid = 4103

for book in booklist:
    if book[0]==bookid:
        print(book)