# coding:utf-8
from common.finish_plan_urlenverment import *
from time import sleep
listt=[

[1,'A story about kindness'],
[1,'A story about sunshine'],
[1,'A story about a journey'],
[1,'A story about music'],
[1,'A story about friendship'],
[1,'A story about courage'],
[1,'A story about growing up'],
[1,'A story about adventure'],
[1,'A story about fairy tales'],
[1,'A story about festivals'],
[1,'A story about family'],
[1,'A story about nature'],
[1,'A story about dreams'],
[1,'A story about being clever'],
[1,'A story about happiness'],
[1,'A story about magic'],
[1,'A story about unity'],
[1,'A story about imagination'],
[1,'A story about miracles'],
[1,'A story about discovery'],
[1,'A story about creation'],
[1,'A story about a princess'],
[1,'A story about a race car'],
[1,'A story about a pirate ship'],
[1,'A story about a spaceship'],
[1,'A story about a superhero'],
[1,'A story about a unicorn'],
[1,'A story about a mermaid'],
[1,'A story about dinosaurs'],
[1,'A story about cowboys'],
[1,'A story about fairies'],
[1,'A story about monsters'],
[1,'A story about ghosts'],
[1,'A story about knights'],
[1,'A story about firefighters'],
[1,'A story about doctors'],
[1,'A story about teachers'],
[1,'A story about astronauts'],
[1,'A story about ninjas'],
[1,'A story about coloring'],
[1,'A story about building blocks'],
[1,'A story about the playground'],
[1,'A story about the beach'],
[1,'A story about the circus'],
[1,'A story about the farm'],
[1,'A story about the jungle'],
[1,'A story about the arctic'],
[1,'A story about the desert'],
[1,'A story about the rainforest'],
[1,'A story about birthday parties'],
[1,'A story about robots'],
[1,'A story about detectives'],
[1,'A story about polar bears'],
[1,'A story about snow days'],
[1,'A story about the future'],
[1,'A story about soccer'],
[1,'A story about cooking'],
[1,'A story about dancing'],
[1,'A story about superpowers'],
[1,'A story about aliens'],
[1,'A story about treasure hunting'],
[1,'A story about camping'],
[1,'A story about amusement parks'],
[1,'A story about helping others'],
[1,'A story about solving mysteries'],
[1,'A story about painting'],
[1,'A story about reading'],
[1,'A story about saving the day'],
[1,'A story about making new friends'],
[1,'A story about trying new things'],
[1,'A story about using imagination'],
[1,'A story about pets'],
[1,'A story about holidays'],
[1,'A story about sports'],
[1,'A story about science'],
[1,'A story about outer space'],
[1,'A story about fantasy worlds'],
[1,'A story about family traditions'],
[1,'A story about explorers'],
[1,'A story about a bear'],
[1,'A story about the moon'],
[1,'A story about a castle'],
[1,'A story about the ocean'],
[1,'A story about a secret garden'],
[1,'A story about a treehouse'],
[1,'A story about baking cookies'],
[1,'A story about snowmen'],
[1,'A story about superheroes'],
[1,'A story about puppies'],
[1,'A story about dolphins'],
[1,'A story about snowboarding'],
[1,'A story about surfing'],
[1,'A story about training falcons'],
[1,'A story about glass blowing'],
[1,'A story about beekeeping'],
[1,'A story about hockey'],
[1,'A story about activism'],
[1,'A story about directing movies'],
[1,'A story about aviation'],
[1,'A story about journalism'],
[1,'A story about birdwatching'],
[2,'小猪历险的故事'],
[2,'随便来一个中文童话'],
[2,'来一则寓言'],
[2,'农夫与蛇的故事'],
[2,'守株待兔'],
[2,'三只小猪的故事'],
[2,'嫦娥奔月的故事'],
[2,'讲一个冒险故事'],
[2,'云彩王国的故事'],
[2,'森林精灵的礼物'],
[2,'月光下的舞会'],
[2,'糖果山洞的秘密'],
[2,'云朵宝宝历险记'],
[2,'音乐盒的魔法'],
[2,'红宝石之旅'],
[2,'银河奇遇记'],
[2,'阳光王子寻找彩虹'],
[2,'音乐精灵的旋律'],
[2,'魔法小屋的冒险'],
[2,'棉花糖的童话世界'],
[2,'紫色小飞象的故事'],
[2,'机器人历险记的故事'],
[2,'小猫钓鱼的故事'],
[2,'森林寻宝的故事'],
[2,'星光游乐园大冒险'],
[2,'糖果乐园探险记'],
[2,'飞翔的音符寻找旋律'],
[2,'彩虹岛的秘密'],
[2,'太空旅行的意外'],
[2,'海洋精灵的泡泡派对'],
[2,'甜点小镇大冒险'],
[2,'月亮王国的童话'],
[2,'讲一个友情的故事'],
[2,'来一个竞技的故事'],
[2,'讲一个梦想的故事'],
[2,'来一个喜剧的故事'],
[2,'讲一个寻找的故事'],
[2,'来一个惊喜的故事'],
[2,'讲一个奇想的故事'],
[2,'来一个回忆的故事'],
[2,'讲一个探险的故事'],
[2,'来一个勇气的故事'],
[2,'讲一个欢乐的故事'],
[2,'来一个勇往的故事'],
[2,'讲一个善良的故事'],
[2,'来一个命运的故事'],
[2,'讲一个奇迹的故事'],
[2,'来一个魔法的故事'],
[2,'彩虹桥的传奇'],
[2,'云彩王国的传说'],
[2,'棉花糖小镇寻宝记'],
[2,'糖果山谷的惊喜'],
[2,'音符王国找到魔法'],
[2,'狐假虎威'],
[2,'画蛇添足'],
[2,'井底之蛙'],
[2,'聚沙成塔'],
[2,'笨鸟先飞'],
[2,'长发公主的故事'],
[2,'小青蛙的故事'],
[2,'来一个童趣的故事'],
[2,'睡美人的故事'],
[2,'讲一个童真的故事'],
[2,'墨守成规的故事'],
[2,'小猫的故事'],
[2,'瞎子摸象'],
[2,'揠苗助长'],
[2,'讲一个野餐的故事'],
[2,'来一个开学的故事'],
[2,'超市里的一天的故事'],
[2,'餐厅里的故事'],
[2,'游乐场的故事'],
[2,'去动物园的故事'],
[2,'玩具店的故事'],
[2,'在公园的一天的故事'],
[2,'去图书馆的故事'],
[2,'游泳池的故事'],
[2,'去海滩的故事'],
[2,'在学校的故事'],
[2,'参观博物馆的故事'],
[2,'乘坐地铁的故事'],
[2,'参加运动会'],
[2,'登山'],
[2,'烹饪的故事'],
[2,'游泳的故事'],
[2,'游泳比赛'],
[2,'绘画的故事'],
[2,'观看电影的故事'],
[2,'春游'],
[2,'烘培蛋糕'],
[2,'螳螂捕蝉'],
[2,'来一个恐龙的故事'],
[2,'讲一个海底的故事'],
[2,'一只小熊寻找蜂蜜的故事'],
[2,'来一个童话王国的故事'],
[2,'小猪的音乐之旅'],
[2,'仓鼠开车去旅行'],
[2,'考拉寻找彩虹的故事'],
[2,'狗狗当警长的故事'],
[3,'关于下雨的诗'],
[3,'关于春天的诗'],
[3,'关于夏天的诗'],
[3,'关于秋天的诗'],
[3,'关于冬天的诗'],
[3,'关于花的诗'],
[3,'关于雨的诗'],
[3,'关于雪的诗'],
[3,'关于月亮的诗'],
[3,'关于山水的诗'],
[3,'关于田园的诗'],
[3,'关于荣誉的诗'],
[3,'关于想象的诗'],
[3,'关于友情的诗'],
[3,'关于亲情的诗'],
[3,'关于爱情的诗'],
[3,'关于人生的诗'],
[3,'关于旅行的诗'],
[3,'关于故乡的诗'],
[3,'关于励志的诗'],
[3,'关于家国的诗'],
[3,'关于劳动的诗'],
[3,'关于战争的诗'],
[3,'关于和平的诗'],
[3,'关于海滩的诗 '],
[3,'关于森林的诗 '],
[3,'关于音乐的诗 '],
[3,'关于阅读的诗 '],
[3,'关于摄影的诗 '],
[3,'关于绘画的诗 '],
[3,'关于登山的诗 '],
[3,'关于画舫的诗 '],
[3,'关于晚霞的诗 '],
[3,'关于繁星的诗 '],
[3,'关于彩虹的诗 '],
[3,'关于五线谱的诗 '],
[3,'关于琴声的诗 '],
[3,'关于童话的诗 '],
[3,'关于微笑的诗 '],
[3,'关于阳光的诗 '],
[3,'关于帆船的诗 '],
[3,'关于晨曦的诗 '],
[3,'关于稻浪的诗'],
[3,'关于寒冬的诗'],
[3,'关于梅花的诗'],
[3,'关于杨柳的诗'],
[3,'关于菊花的诗'],
[3,'关于桃花的诗'],
[3,'关于星月的诗'],
[3,'关于海洋的诗'],
[3,'关于山川的诗'],
[3,'关于飞瀑的诗'],
[3,'关于母亲的诗'],
[3,'关于田野的诗'],
[3,'关于劳作的诗'],
[3,'关于渔樵的诗'],
[3,'关于江河的诗'],
[3,'关于平原的诗'],
[3,'关于沙漠的诗'],
[3,'关于桃源的诗'],
[3,'关于丰收的诗'],
[3,'关于奇想的诗'],
[3,'关于亲友的诗'],
[3,'关于思念的诗'],
[3,'关于乡愁的诗'],
[3,'关于离别的诗'],
[3,'关于团圆的诗'],
[3,'关于报国的诗'],
[3,'关于忧国的诗'],
[3,'关于洞庭的诗'],
[3,'关于泾水的诗'],
[3,'关于长江的诗'],
[3,'关于黄河的诗'],
[3,'关于明月的诗'],
[3,'关于流星的诗'],
[3,'关于桂花的诗'],
[3,'关于竹林的诗'],
[3,'关于钓叟的诗'],
[3,'关于渔家的诗'],
[3,'关于秋景的诗'],
[3,'关于寒食的诗'],
[3,'关于清明的诗'],
[3,'关于端午的诗'],
[3,'关于中秋的诗'],
[3,'关于重阳的诗'],
[3,'关于寿诞的诗'],
[3,'关于远方的诗'],
[3,'关于游子的诗'],
[3,'关于黄鹤的诗'],
[3,'关于白云的诗'],
[3,'关于绿水的诗'],
[3,'关于村舍的诗'],
[3,'关于童年的诗'],
[3,'关于大海的诗 '],
[3,'关于星空的诗 '],
[3,'关于流水的诗'],
[3,'关于季节的诗'],
[3,'关于兴衰的诗'],
[4,'How is you 有错吗'],
[4,'I gets up early. 有错吗?'],
[4,'You is my friend. 有错吗?'],
[4,'He runned fast. 有错吗?'],
[4,'She eated a apple. 有错吗?'],
[4,'I goed to school. 有错吗?'],
[4,'It was three sheeps. 有错吗?'],
[4,'She putted the toys. 有错吗?'],
[4,'They is sisters. 有错吗?'],
[4,'He writed a letter. 有错吗?'],
[4,'The dog eated the bone. 有错吗?'],
[4,'She readed that book. 有错吗?'],
[4,'I seed the birds. 有错吗?'],
[4,'He taked the ball. 有错吗?'],
[4,'She runned very fast. 有错吗?'],
[4,'The mans worked hard. 有错吗?'],
[4,'The childs played. 有错吗?'],
[4,'She drinked the milk. 有错吗?'],
[4,'He comed yesterday. 有错吗?'],
[4,'I goed there before. 有错吗?'],
[4,'He eated a sandwich. 有错吗?'],
[4,'She drinked water. 有错吗?'],
[4,'The fox runned away. 有错吗?'],
[4,'She readed a story. 有错吗?'],
[4,'They is teachers. 有错吗?'],
[4,'I writed a letter. 有错吗?'],
[4,'He taked a photo. 有错吗?'],
[4,'There was five books. 有错吗?'],
[4,'This is mines book. 有错吗?'],
[4,'She runned home. 有错吗?'],
[4,'He comed home late.有错吗?'],
[4,'She seed the star. 有错吗?'],
[4,'I gived her a gift. 有错吗?'],
[4,'They eated already. 有错吗?'],
[4,'He drinked water. 有错吗?'],
[4,'She maked a cake. 有错吗?'],
[4,'Those is my toys. 有错吗?'],
[4,'I readed that story. 有错吗?'],
[4,'She runned fast. 有错吗?'],
[4,'He goed to work. 有错吗?'],
[4,'I writed it myself. 有错吗?'],
[4,'She buyed some apples. 有错吗?'],
[4,'He taked a rest. 有错吗?'],
[4,'She eated breakfast. 有错吗?'],
[4,'I drinked milk. 有错吗?'],
[4,'He runned away. 有错吗?'],
[4,'She readed a book. 有错吗?'],
[4,'I seed the rainbow. 有错吗?'],
[4,'He swimmed in the pool. 有错吗?'],
[4,'She putted it there. 有错吗?'],
[4,'I leaved school early. 有错吗?'],
[4,'It legged the table. 有错吗?'],
[4,'I runned very fast. 有错吗?'],
[4,'I comed here yesterday. 有错吗?'],
[4,'He eated an apple. 有错吗?'],
[4,'We goed to the park. 有错吗?'],
[4,'She drinked juice. 有错吗?'],
[4,'They rided bikes. 有错吗?'],
[4,'I taked a taxi. 有错吗?'],
[4,'He runned very fast. 有错吗?'],
[4,'They is playing. 有错吗?'],
[4,'Do you have any potato chips? 有错吗?'],
[4,'There are so many leaf on the ground. 有错吗?'],
[4,'I need two spoon for the cake. 有错吗?'],
[4,'The boy is holding five mouses. 有错吗?'],
[4,'She was wearing a jeans. 有错吗?'],
[4,'I only have one shoe to wear. 有错吗?'],
[4,'The dog eated his dinner. 有错吗?'],
[4,' She seed the butterfly. 有错吗? '],
[4,'I writed in my book. 有错吗?'],
[4,' He readed a story. 有错吗? '],
[4,'She runned to her mom. 有错吗? '],
[4,'I maked a card. 有错吗?'],
[4,' The bird flyed away. 有错吗?'],
[4,'I has a book. 有错吗?'],
[4,'Where you go yesterday? 有错吗?'],
[4,'I glad to see you. 有错吗?'],
[4,'She drink milk every day. 有错吗?'],
[4,'We eat apple yesterday. 有错吗?'],
[4,'Do you can sing? 有错吗?'],
[4,'I feeled happy. 有错吗?'],
[4,'You readed the book. 有错吗?'],
[4,'I goed there last week. 有错吗?'],
[4,'He maked a cake. 有错吗?'],
[4,'They founded the city. 有错吗?'],
[4,'We buyed some toys. 有错吗?'],
[4,'She drawed a picture. 有错吗?'],
[4,'I drived to school. 有错吗?'],
[4,'She taked the bus. 有错吗?'],
[4,'They leaved early. 有错吗?'],
[4,'I am eats breakfast every morning. 有错吗?'],
[4,'He is liking to play soccer. 有错吗?'],
[4,'She is writes in her diary every night. 有错吗?'],
[4,'My brother and I is going to the park. 有错吗?'],
[4,'The dogs is running in the yard. 有错吗?'],
[4,'There is lots of toys in my room. 有错吗?'],
[4,'My friends is coming over to play. 有错吗?'],
[4,'The box of crayons is sitting on the table. 有错吗?'],
[4,'The boys is playing video games. 有错吗?'],
[4,'There was many people at the party. 有错吗?'],
[5,'天空为什么是蓝色的'],
[5,'你知道李白吗'],
[5,'raz是什么'],
[5,'熊猫的英文'],
[5,'谁发明了电灯泡?'],
[5,'你喜欢看什么类型的电影?'],
[5,'现在北京时间是几点?'],
[5,'早上好怎么说英语?'],
[5,'你最喜欢的水果是什么?'],
[5,'长城主要建在哪里?'],
[5,'你最喜欢哪个城市?'],
[5,'你喜欢看书吗?'],
[5,'你喜欢玩滑梯吗?'],
[5,'我们为什么要睡觉?'],
[5,'你知道屈原吗?'],
[5,'apple是什么意思?'],
[5,'长城有多长?'],
[5,'你知道苏东坡吗?'],
[5,'cat是什么动物?'],
[5,'恐龙为什么会灭绝?'],
[5,'你知道杜甫吗?'],
[5,'dog是什么意思?'],
[5,'月亮是怎么形成的?'],
[5,'你知道白居易吗?'],
[5,'panda是什么动物?'],
[5,'蝴蝶从哪里来?'],
[5,'你知道王维吗?'],
[5,'horse是什么动物?'],
[5,'月球上有没有水?'],
[5,'你知道陆游吗?'],
[5,'bird是什么意思?'],
[5,'我们为什么要刷牙?'],
[5,'你知道苏辙吗?'],
[5,'flower是什么意思?'],
[5,'蜗牛有没有眼睛?'],
[5,'你知道辛弃疾吗?'],
[5,'tree是什么意思?'],
[5,'鲸鱼为什么会搁浅?'],
[5,'apple是什么水果?'],
[5,'我们为什么要洗澡?'],
[5,'世界上最高的山峰是哪座山?'],
[5,'你喜欢什么颜色?'],
[5,'I love you怎么说中文?'],
[5,'你最喜欢吃什么零食?'],
[5,'为什么要刷牙?'],
[5,'中国有多少个省?'],
[5,'你最喜欢什么季节?'],
[5,'Hello怎么说中文?'],
[5,'你喜欢玩什么运动?'],
[5,'世界上最长的河流是哪条河?'],
[5,'你喜欢看绘本还是小说?'],
[5,'哪个乐器最好听?'],
[5,'太空是什么意思?'],
[5,'喜欢什么类型的游戏?'],
[5,'超级英雄是什么意思?'],
[5,'想养什么宠物?'],
[5,'Goodbye怎么说中文?'],
[5,'你最喜欢哪个童话故事?'],
[5,'为什么会有地震?'],
[5,'你知道白居易吗?你知道岳飞吗?'],
[5,'你喜欢玩游戏吗?'],
[5,'古代使用什么交通工具?'],
[5,'你最喜欢什么水果口味的冰淇淋?'],
[5,'See you tomorrow怎么说中文?'],
[5,'你喜欢什么季节?'],
[5,'蜘蛛有几条腿?'],
[5,'你知道杜牧吗?'],
[5,'bike是一种交通工具吗?'],
[5,'人体内有多少根骨头?'],
[5,'你最喜欢哪个卡通人物?'],
[5,'你喜欢哪种运动?'],
[5,'中国有多少个民族?'],
[5,'你喜欢看戏曲吗?'],
[5,'Good night怎么说中文?'],
[5,'你最喜欢哪种动物?'],
[5,'你知道李商隐吗?'],
[5,'cat有几条腿?'],
[5,'世界上最长的河流是哪条?'],
[5,'你喜欢吃酸酸甜甜的食物吗?'],
[5,'Thank you怎么说中文?'],
[5,'你最喜欢什么颜色?'],
[5,'北京的英文怎么说?'],
[5,'dog是人类的朋友吗?'],
[5,'中国有多少个世界遗产?'],
[5,'你喜欢画画吗?'],
[5,'See you later怎么说中文?'],
[5,'天上的星星是什么?'],
[5,'panda吃竹子吗?'],
[6,'小汽车简笔画'],

]

def aicheck(infoo,typpe):
    baseurl=urlenverment(1)
    url=baseurl+'v1/aigc/chat'

    header={'Authorization':'Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxNjgxMTA3NjgwMTg0MzQwNDgxIiwic3ViIjoie1wiaWRcIjoxNjgxMTA3NjgwMTg0MzQwNDgxLFwibW9iaWxlXCI6XCIrODYxNzM0NTA0MzM2NVwifSIsImV4cCI6MTcwODg0OTcwMn0.65WwfziNOw89Cfr3fcjmkT-5w-95WHhN_VuhyaKBBOtV6I7dCSbEFtez2vhKSQhTCdlwM033PapBerLOikRQ2g',
            'Sn':'S1DEV003'}

    data={"content":infoo,"time":1693300995813,"type":typpe,"uid":1681107680184340481}

    requestss=requests.post(url=url,json=data,headers=header)
    return requestss.status_code,requestss.text


if __name__ == '__main__':


   # infffo= aicheck('苏轼的诗',3)[1]
   # lennnn=len(infffo)
   # print(lennnn)
   # print(infffo)

#2975  code==4666

    errorlist=[]
    for ci in listt:
        infoo=ci[1]
        typpe=ci[0]
        # print(ci)
        try :
            sleep(1)
            innfo = aicheck(infoo, typpe)
            codee = innfo[0]
            lennnn=len(innfo[1])
            if  codee == "4666" or lennnn < 2800:
                errorlist.append(ci)
                print(ci,"ERROR!")
            else:
                print(ci,"OK!")
        except:
            sleep(30)
            innfo = aicheck(infoo, typpe)
            codee = innfo[0]
            lennnn = len(innfo[1])
            if codee == "4666" or lennnn < 2800:
                errorlist.append(ci)
                print(ci, "ERROR!")
            else:
                print(ci, "OK!")
    print(errorlist)